# Generated by Django 3.2.23 on 2023-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
