# Generated by Django 3.2.23 on 2023-11-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0002_auto_20231128_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
