# Generated by Django 3.2.23 on 2023-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marksheet', '0003_marksheet_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksheet',
            name='email',
            field=models.EmailField(default='demo@gmail.com', max_length=255, null=True),
        ),
    ]
